//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGA.Helper.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resMSTMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resMSTMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OGA.Helper.Message.resMSTMessage", typeof(resMSTMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดในการลบข้อมูล {0}.
        /// </summary>
        internal static string AlertDelete {
            get {
                return ResourceManager.GetString("AlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดในการบันทึกการแก้ไขข้อมูล {0}.
        /// </summary>
        internal static string AlertEdit {
            get {
                return ResourceManager.GetString("AlertEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดในการบันทึกข้อมูล {0}.
        /// </summary>
        internal static string AlertSave {
            get {
                return ResourceManager.GetString("AlertSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการลบข้อมูล {0} : {1} นี้ใช่หรือไม่.
        /// </summary>
        internal static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการลบข้อมูล {0} : {1} เรียบร้อยแล้ว.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อมูล {0} : {1} นี้แล้วในระบบ.
        /// </summary>
        internal static string Doopplicate {
            get {
                return ResourceManager.GetString("Doopplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการบันทึกการแก้ไขข้อมูล {0} : {1} นี้ใช่หรือไม่.
        /// </summary>
        internal static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกการแแก้ไขข้อมูล {0} : {1} เรียบร้อยแล้ว.
        /// </summary>
        internal static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลบข้อมูลได้ เนื่องจากข้อมูล {0} ถูกใช้งานอยู่!.
        /// </summary>
        internal static string ErrorDeleteRelation {
            get {
                return ResourceManager.GetString("ErrorDeleteRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1} นี มีอยู่แล้วในระบบ!.
        /// </summary>
        internal static string ErrorDuplicateData {
            get {
                return ResourceManager.GetString("ErrorDuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คีย์ซ้ำ ข้อมูลนี้มีอยู่ในระบบแล้ว!.
        /// </summary>
        internal static string ErrorDuplicateKey {
            get {
                return ResourceManager.GetString("ErrorDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดขระทำการโหลดข้อมูล Bin.
        /// </summary>
        internal static string ErrorLoadBin {
            get {
                return ResourceManager.GetString("ErrorLoadBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดในการโหลดข้อมูล Bin Category.
        /// </summary>
        internal static string ErrorLoadBinCategory {
            get {
                return ResourceManager.GetString("ErrorLoadBinCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดขระทำการโหลดข้อมูล Bin Type.
        /// </summary>
        internal static string ErrorLoadBinType {
            get {
                return ResourceManager.GetString("ErrorLoadBinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดขระทำการโหลดข้อมูล Bin Zone.
        /// </summary>
        internal static string ErrorLoadBinZone {
            get {
                return ResourceManager.GetString("ErrorLoadBinZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดขระทำการโหลดข้อมูล Company.
        /// </summary>
        internal static string ErrorLoadCompany {
            get {
                return ResourceManager.GetString("ErrorLoadCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดขระทำการโหลดข้อมูล Plant.
        /// </summary>
        internal static string ErrorLoadPlant {
            get {
                return ResourceManager.GetString("ErrorLoadPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดขระทำการโหลดข้อมูล Site.
        /// </summary>
        internal static string ErrorLoadSite {
            get {
                return ResourceManager.GetString("ErrorLoadSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดขระทำการโหลดข้อมูล Warehouse.
        /// </summary>
        internal static string ErrorLoadWarehouse {
            get {
                return ResourceManager.GetString("ErrorLoadWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อผิดพลาด : {0}.
        /// </summary>
        internal static string ErrorOnTryCatch {
            get {
                return ResourceManager.GetString("ErrorOnTryCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล {0} : {1} นี้ในระบบ.
        /// </summary>
        internal static string NotfoundMaster {
            get {
                return ResourceManager.GetString("NotfoundMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการทำการบันทึกข้อมูล {0} : {1} นี้ใช่หรือไม่ .
        /// </summary>
        internal static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการบันทึกข้อมูล {0} : {1} เรียบร้อยแล้ว.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาทำการระบุข้อมูล {0}.
        /// </summary>
        internal static string ValidateSelectData {
            get {
                return ResourceManager.GetString("ValidateSelectData", resourceCulture);
            }
        }
    }
}
