//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGA.Helper.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSystemMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSystemMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OGA.Helper.Message.resSystemMessage", typeof(resSystemMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - - - - -ไม่มีข้อมูล - - - - -.
        /// </summary>
        internal static string CaptionDefaultComboNoData {
            get {
                return ResourceManager.GetString("CaptionDefaultComboNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการปิดโปรแกรม ใช่หรือไม่.
        /// </summary>
        internal static string ConfirmCloseProgram {
            get {
                return ResourceManager.GetString("ConfirmCloseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการลบข้อมูลบนหน้าจอ ใช่ หรือ ไม่ ?.
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อกับ Server ได้ ! กรุณาลองอีกครั้ง หรือติดต่อผู้ดูแลระบบ.
        /// </summary>
        internal static string ConnectServerFail {
            get {
                return ResourceManager.GetString("ConnectServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การแสดงข้อมูลใน Combo Box ผิดพลาด !.
        /// </summary>
        internal static string ErrorBindComboData {
            get {
                return ResourceManager.GetString("ErrorBindComboData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การยกเลิก เสร็จสมบูรณ์ !.
        /// </summary>
        internal static string ResultCancelComplete {
            get {
                return ResourceManager.GetString("ResultCancelComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การลบข้อมูล เสร็จสมบูรณ์ !.
        /// </summary>
        internal static string ResultDeleteComplete {
            get {
                return ResourceManager.GetString("ResultDeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การบันทึก เสร็จสมบูรณ์ !.
        /// </summary>
        internal static string ResultSaveComplete {
            get {
                return ResourceManager.GetString("ResultSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การบันทึกไม่สมบูรณ์ !.
        /// </summary>
        internal static string ResultSaveFailed {
            get {
                return ResourceManager.GetString("ResultSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกข้อมูลก่อน !.
        /// </summary>
        internal static string ValidateSelectComboData {
            get {
                return ResourceManager.GetString("ValidateSelectComboData", resourceCulture);
            }
        }
    }
}
